import base64
BL = chr(123)
BR = chr(125)
DQ = chr(34)
FMT2 = 'format!(' + DQ + BL + BR + DQ + ', '
FMT3 = 'format!(' + DQ + BL + BR + BL + BR + DQ + ', '
def wchunk(idx, text):
    path = 'd:/game/mytemple/chunk_' + str(idx).zfill(2) + '.b64'
    with open(path, 'w') as f:
        f.write(base64.b64encode(text.encode('utf-8')).decode('ascii'))
    print('Wrote chunk', idx, ':', len(text), 'chars')
print('builder ready')

# Write chunk 1 - beginning of new methods
def make_chunk1():
    L = []
    L.append('encoding: ' + DQ + 'utf-8' + DQ + '.to_string(),')
    L.append('')
    L.append('        ' + BR)
    L.append('')
    L.append('    ' + BR)
    L.append('')
    L.append('    /// Move a file or folder to a target folder')
    L.append('    pub async fn move_entry(&self, source: &str, target_folder: &str) -> anyhow::Result<(String, bool)> ' + BL)
    L.append('        let src = self.normalize_doc_path(source)?;')
    L.append('        let tgt = self.normalize_doc_path(target_folder)?;')
    L.append('')
    L.append('        let src_abs = Path::new(&src.absolute);')
    L.append('        let tgt_abs = Path::new(&tgt.absolute);')
    L.append('')
    L.append('        if !src_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Source not found' + DQ + ');')
    L.append('        ' + BR)
    L.append('        if !tgt_abs.exists() || !tgt_abs.is_dir() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Target folder not found' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        let is_dir = src_abs.is_dir();')
    L.append('        if !is_dir && !src.relative.ends_with(' + DQ + '.md' + DQ + ') ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Only .md files can be moved' + DQ + ');')
    L.append('        ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(1, make_chunk1())

def make_chunk2():
    L = []
    L.append('        // Prevent moving folder into itself')
    L.append('        if is_dir ' + BL)
    L.append('            let src_root = ' + FMT3 + 'src.absolute, std::path::MAIN_SEPARATOR);')
    L.append('            let tgt_root = ' + FMT3 + 'tgt.absolute, std::path::MAIN_SEPARATOR);')
    L.append('            if tgt_root.starts_with(&src_root) ' + BL)
    L.append('                anyhow::bail!(' + DQ + 'Folder cannot be moved into itself' + DQ + ');')
    L.append('            ' + BR)
    L.append('        ' + BR)
    L.append('')
    L.append('        let dest_name = src_relative_name(&src.relative);')
    L.append('        let dest_relative = ' + FMT2 + 'tgt.relative, dest_name);')
    L.append('        let dest = self.normalize_doc_path(&dest_relative)?;')
    L.append('        let dest_abs = Path::new(&dest.absolute);')
    L.append('')
    L.append('        if src.absolute == dest.absolute ' + BL)
    L.append('            return Ok((src.ref, false));')
    L.append('        ' + BR)
    L.append('        if dest_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Destination already exists' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        if src.workspace_id == tgt.workspace_id ' + BL)
    L.append('            std::fs::rename(&src.absolute, &dest.absolute)?;')
    L.append('        ' + BR + ' else ' + BL)
    L.append('            // Cross-workspace: copy then delete')
    L.append('            copy_dir_all(&src.absolute, &dest.absolute)?;')
    L.append('            if is_dir ' + BL)
    L.append('                std::fs::remove_dir_all(&src.absolute)?;')
    L.append('            ' + BR + ' else ' + BL)
    L.append('                std::fs::remove_file(&src.absolute)?;')
    L.append('            ' + BR)
    L.append('        ' + BR)
    L.append('')
    L.append('        self.refresh_cache().await?;')
    L.append('        Ok((dest.ref, is_dir))')
    L.append('    ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(2, make_chunk2())

def make_chunk3():
    L = []
    L.append('')
    L.append('    /// Copy a file or folder to a target folder')
    L.append('    pub async fn copy_entry(&self, source: &str, target_folder: &str) -> anyhow::Result<String> ' + BL)
    L.append('        let src = self.normalize_doc_path(source)?;')
    L.append('        let tgt = self.normalize_doc_path(target_folder)?;')
    L.append('')
    L.append('        let src_abs = Path::new(&src.absolute);')
    L.append('        let tgt_abs = Path::new(&tgt.absolute);')
    L.append('')
    L.append('        if !src_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Source not found' + DQ + ');')
    L.append('        ' + BR)
    L.append('        if !tgt_abs.exists() || !tgt_abs.is_dir() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Target folder not found' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        let dest_name = src_relative_name(&src.relative);')
    L.append('        let dest_relative = ' + FMT2 + 'tgt.relative, dest_name);')
    L.append('        let dest = self.normalize_doc_path(&dest_relative)?;')
    L.append('        let dest_abs = Path::new(&dest.absolute);')
    L.append('')
    L.append('        if dest_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Destination already exists' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        copy_dir_all(&src.absolute, &dest.absolute)?;')
    L.append('        self.refresh_cache().await?;')
    L.append('        Ok(dest.ref)')
    L.append('    ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(3, make_chunk3())

def make_chunk4():
    L = []
    L.append('')
    L.append('    /// Rename a file or folder')
    L.append('    pub async fn rename_entry(&self, path: &str, new_name: &str) -> anyhow::Result<String> ' + BL)
    L.append('        let src = self.normalize_doc_path(path)?;')
    L.append('        let src_abs = Path::new(&src.absolute);')
    L.append('')
    L.append('        if !src_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Source not found' + DQ + ');')
    L.append('        ' + BR)
    L.append('        if src.relative.is_empty() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Workspace root cannot be renamed' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        let is_dir = src_abs.is_dir();')
    L.append('        let mut safe_name = new_name.to_string();')
    L.append('        if !is_dir && !safe_name.ends_with(' + DQ + '.md' + DQ + ') ' + BL)
    L.append('            safe_name = ' + FMT2 + 'safe_name);')
    L.append('        ' + BR)
    L.append('        safe_name = sanitize_name(&safe_name);')
    L.append('        if safe_name.is_empty() || safe_name == ' + DQ + '.' + DQ + ' || safe_name == ' + DQ + '..' + DQ + ' ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Invalid name' + DQ + ');')
    L.append('        ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(4, make_chunk4())

# Continue chunk 4 - rest of rename_entry
def make_chunk4b():
    L = []
    L.append('')
    L.append('        let parent_dir = src_abs.parent().unwrap_or_else(|| Path::new(' + DQ + '.' + DQ + '));')
    L.append('        let dest_abs = parent_dir.join(&safe_name);')
    L.append('')
    L.append('        if dest_abs == src_abs ' + BL)
    L.append('            return Ok(src.ref);')
    L.append('        ' + BR)
    L.append('        if dest_abs.exists() ' + BL)
    L.append('            anyhow::bail!(' + DQ + 'Target already exists' + DQ + ');')
    L.append('        ' + BR)
    L.append('')
    L.append('        std::fs::rename(&src.absolute, &dest_abs)?;')
    L.append('')
    L.append('        let parent_rel = src.relative.rsplit_once(' + DQ + '/' + DQ + ').map(|(p, _)| p).unwrap_or(' + DQ + DQ + ');')
    L.append('        let new_relative = if parent_rel.is_empty() ' + BL)
    L.append('            safe_name')
    L.append('        ' + BR + ' else ' + BL)
    L.append('            ' + FMT3 + 'parent_rel, safe_name)')
    L.append('        ' + BR)
    L.append('        let new_ref = ' + FMT3 + 'src.workspace_id, new_relative);')
    L.append('')
    L.append('        self.refresh_cache().await?;')
    L.append('        Ok(new_ref)')
    L.append('    ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(5, make_chunk4b())

def make_chunk6():
    L = []
    L.append('')
    L.append('    /// Get frontmatter keys and values from a markdown file')
    L.append('    pub async fn get_frontmatter(&self, path: &str) -> anyhow::Result<serde_json::Value> ' + BL)
    L.append('        let doc = self.read_file(path).await?;')
    L.append('        let content = &doc.content;')
    L.append('        let (_, after) = extract_frontmatter_block(content);')
    L.append('        let map = normalize_frontmatter(after);')
    L.append('        serde_json::to_value(map).map_err(|e| anyhow::anyhow!(e))')
    L.append('    ' + BR)
    L.append('')
    L.append('    /// Get a short summary of frontmatter (for listing)')
    L.append('    pub async fn preview_frontmatter(&self, path: &str) -> anyhow::Result<serde_json::Value> ' + BL)
    L.append('        let doc = self.read_file(path).await?;')
    L.append('        let content = &doc.content;')
    L.append('        let summary = frontmatter_summary(content);')
    L.append('        serde_json::to_value(summary).map_err(|e| anyhow::anyhow!(e))')
    L.append('    ' + BR)
    L.append('')
    L.append('    /// Replace frontmatter in a markdown file with new values')
    L.append('    pub async fn apply_frontmatter(&self, path: &str, values: serde_json::Value) -> anyhow::Result<String> ' + BL)
    L.append('        let doc = self.read_file(path).await?;')
    L.append('        let content = &doc.content;')
    L.append('        let (_, body) = extract_frontmatter_block(content);')
    L.append('        let mut lines: Vec<String> = Vec::new();')
    L.append('        lines.push(' + DQ + '---' + DQ + '.to_string());')
    L.append('        if let Some(obj) = values.as_object() ' + BL)
    L.append('            for (key, val) in obj ' + BL)
    L.append('                let line = match val ' + BL)
    L.append('                    serde_json::Value::String(s) => ' + FMT3 + 'key, s),')
    L.append('                    serde_json::Value::Number(n) => ' + FMT3 + 'key, n),')
    L.append('                    serde_json::Value::Bool(b) => ' + FMT3 + 'key, b),')
    L.append('                    serde_json::Value::Array(arr) => ' + BL)
    L.append('                        let items: Vec<String> = arr.iter().filter_map(|v| v.as_str().map(|s| s.to_string())).collect();')
    L.append('                        ' + FMT3 + 'key, items.join(' + DQ + ', ' + DQ + '))')
    L.append('                    ' + BR)
    L.append('                    _ => ' + FMT3 + 'key, val),')
    L.append('                ' + BR + ';')
    L.append('                lines.push(line);')
    L.append('            ' + BR)
    L.append('        ' + BR)
    L.append('        lines.push(' + DQ + '---' + DQ + '.to_string());')
    L.append('        lines.push(' + DQ + DQ + ');')
    L.append('        let mut new_content = lines.join(' + DQ + chr(10) + DQ + ');')
    L.append('        new_content.push_str(body);')
    L.append('        self.save_file(path, &new_content).await?;')
    L.append('        Ok(new_content)')
    L.append('    ' + BR)
    return chr(10).join(L) + chr(10)

wchunk(6, make_chunk6())
