import base64
BL = chr(123)
BR = chr(125)
DQ = chr(34)
BN = chr(92)
FMT2 = 'format!(' + DQ + BL + BR + DQ + ', '
FMT3 = 'format!(' + DQ + BL + BR + BL + BR + DQ + ', '
NL = BN + 'n'
CR = BN + 'r'
NL_RUST = DQ + NL + DQ
CR_RUST = DQ + CR + DQ
NLN_RUST = DQ + NL + '---' + DQ

L = []
L.append('')
L.append('/// Extract YAML frontmatter block from markdown content.')
L.append('/// Returns (frontmatter_body, remaining_content).')
L.append('fn extract_frontmatter_block(content: &str) -> (&str, &str) ' + BL)
L.append('    let bytes = content.as_bytes();')
L.append('    if bytes.len() < 8 ' + BL)
L.append('        return (' + DQ + DQ + ', content);')
L.append('    ' + BR)
L.append('    // Check for opening ---')
L.append('    if !bytes.starts_with(b' + DQ + '---' + DQ + ') ' + BL)
L.append('        return (' + DQ + DQ + ', content);')
L.append('    ' + BR)
L.append('    // Find closing ---')
L.append('    let after_open = &content[3..];')
L.append('    let close_idx = after_open.find(' + NLN_RUST + ').or_else(|| after_open.find(' + DQ + '---' + DQ + '));')
L.append('    match close_idx ' + BL)
L.append('        Some(idx) => ' + BL)
L.append('            let fm = after_open[..idx].trim();')
L.append('            let rest_start = idx + 3;')
L.append('            let rest = after_open[rest_start..].trim_start_matches(' + NL_RUST + ').trim_start_matches(' + CR_RUST + ').trim_start_matches(' + NL_RUST + ');')
L.append('            (fm, rest)')
L.append('        ' + BR)
L.append('        None => (' + DQ + DQ + ', content)')
L.append('    ' + BR)
L.append('' + BR)
L.append('')
L.append('/// Parse frontmatter body into a simple map of key -> string')
L.append('fn normalize_frontmatter(fm_body: &str) -> std::collections::BTreeMap<String, String> ' + BL)
L.append('    let mut map = std::collections::BTreeMap::new();')
L.append('    for line in fm_body.lines() ' + BL)
L.append('        let l = line.trim();')
L.append('        if l.is_empty() || l.starts_with(' + DQ + '#' + DQ + ') ' + BL)
L.append('            continue;')
L.append('        ' + BR)
L.append('        if let Some(colon) = l.find(' + DQ + ':' + DQ + ') ' + BL)
L.append('            let key = l[..colon].trim().trim_matches(' + DQ + chr(39) + DQ + ').trim_matches(' + DQ + chr(34) + DQ + ');')
L.append('            let val = l[colon+1..].trim().trim_matches(' + DQ + chr(39) + DQ + ').trim_matches(' + DQ + chr(34) + DQ + ');')
L.append('            if !key.is_empty() ' + BL)
L.append('                map.insert(key.to_string(), val.to_string());')
L.append('            ' + BR)
L.append('        ' + BR)
L.append('    ' + BR)
L.append('    map')
L.append('' + BR)
L.append('')
L.append('/// Build a small summary (title, date, tags) from markdown content')
L.append('fn frontmatter_summary(content: &str) -> std::collections::BTreeMap<String, String> ' + BL)
L.append('    let (fm, _) = extract_frontmatter_block(content);')
L.append('    let map = normalize_frontmatter(fm);')
L.append('    let mut summary = std::collections::BTreeMap::new();')
L.append('    for key in [' + DQ + 'title' + DQ + ', ' + DQ + 'date' + DQ + ', ' + DQ + 'tags' + DQ + '] ' + BL)
L.append('        if let Some(v) = map.get(key) ' + BL)
L.append('            summary.insert(key.to_string(), v.clone());')
L.append('        ' + BR)
L.append('    ' + BR)
L.append('    summary')
L.append('' + BR)

text = chr(10).join(L) + chr(10)
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/chunk_09.b64', 'w') as f:
    f.write(encoded)
print('Wrote chunk 9:', len(text), 'chars')
