# -*- coding: utf-8 -*-
import base64
BL = chr(123)
BR = chr(125)
DQ = chr(34)
BN = chr(92)

def make_handler_file():
    parts = []
    parts.append('')
    parts.append('// File Operations (Phase 2)')
    parts.append('')
    parts.append('#[derive(Deserialize)]')
    parts.append('struct MoveFileRequest ' + BL)
    parts.append('    source: String,')
    parts.append('    target_folder: String,')
    parts.append(BR)
    parts.append('')
    parts.append('async fn move_file(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Json(req): Json<MoveFileRequest>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.move_entry(&req.source, &req.target_folder).await ' + BL)
    parts.append('        Ok((path, is_dir)) => raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true, ' + DQ + 'path' + DQ + ': path, ' + DQ + 'isDir' + DQ + ': is_dir' + BR + ')),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_handler_file()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk1.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk1:', len(text), 'chars')

def make_chunk2():
    parts = []
    parts.append('')
    parts.append('#[derive(Deserialize)]')
    parts.append('struct CopyFileRequest ' + BL)
    parts.append('    source: String,')
    parts.append('    target_folder: String,')
    parts.append(BR)
    parts.append('')
    parts.append('async fn copy_file(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Json(req): Json<CopyFileRequest>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.copy_entry(&req.source, &req.target_folder).await ' + BL)
    parts.append('        Ok(path) => raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true, ' + DQ + 'path' + DQ + ': path' + BR + ')),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    parts.append('')
    parts.append('#[derive(Deserialize)]')
    parts.append('struct RenameFileRequest ' + BL)
    parts.append('    path: String,')
    parts.append('    new_name: String,')
    parts.append(BR)
    parts.append('')
    parts.append('async fn rename_file(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Json(req): Json<RenameFileRequest>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.rename_entry(&req.path, &req.new_name).await ' + BL)
    parts.append('        Ok(path) => raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true, ' + DQ + 'path' + DQ + ': path' + BR + ')),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_chunk2()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk2.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk2:', len(text), 'chars')

def make_chunk3():
    parts = []
    parts.append('')
    parts.append('// Frontmatter handlers')
    parts.append('')
    parts.append('async fn get_frontmatter_handler(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Path(path): Path<String>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.get_frontmatter(&path).await ' + BL)
    parts.append('        Ok(map) => raw_json(map),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    parts.append('')
    parts.append('async fn preview_frontmatter_handler(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Path(path): Path<String>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.preview_frontmatter(&path).await ' + BL)
    parts.append('        Ok(summary) => raw_json(summary),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    parts.append('')
    parts.append('async fn apply_frontmatter_handler(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Path(path): Path<String>,')
    parts.append('    Json(values): Json<serde_json::Value>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.apply_frontmatter(&path, values).await ' + BL)
    parts.append('        Ok(content) => raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true, ' + DQ + 'content' + DQ + ': content' + BR + ')),')
    parts.append('        Err(e) => json_err(StatusCode::BAD_REQUEST, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    parts.append('')
    parts.append('// Detailed health')
    parts.append('')
    parts.append('async fn health_detailed(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    match state.app.health_check().await ' + BL)
    parts.append('        Ok(info) => raw_json(info),')
    parts.append('        Err(e) => json_err(StatusCode::INTERNAL_SERVER_ERROR, e.to_string()),')
    parts.append('    ' + BR)
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_chunk3()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk3.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk3:', len(text), 'chars')

def make_chunk4():
    parts = []
    parts.append('')
    parts.append('// System operations')
    parts.append('')
    parts.append('#[derive(Deserialize)]')
    parts.append('struct OpenFolderRequest ' + BL)
    parts.append('    path: String,')
    parts.append(BR)
    parts.append('')
    parts.append('async fn open_folder(')
    parts.append('    State(state): State<Arc<ServerState>>,')
    parts.append('    Json(req): Json<OpenFolderRequest>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    let path = std::path::Path::new(&req.path);')
    parts.append('    if !path.exists() ' + BL)
    parts.append('        return json_err(StatusCode::NOT_FOUND, ' + DQ + 'Path not found' + DQ + ');')
    parts.append('    ' + BR)
    parts.append('    ' + BN + 'cfg(target_os = ' + DQ + 'windows' + DQ + ')]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'explorer' + DQ + ').arg(&req.path).creation_flags(0x08000000).spawn();')
    parts.append('    ' + BR)
    parts.append('    ' + BN + 'cfg(target_os = ' + DQ + 'macos' + DQ + ')]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'open' + DQ + ').arg(&req.path).spawn();')
    parts.append('    ' + BR)
    parts.append('    ' + BN + 'cfg(all(unix, not(target_os = ' + DQ + 'macos' + DQ + ')))]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'xdg-open' + DQ + ').arg(&req.path).spawn();')
    parts.append('    ' + BR)
    parts.append('    raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true' + BR + '))')
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_chunk4()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk4.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk4:', len(text), 'chars')

def make_chunk5():
    parts = []
    parts.append('')
    parts.append('#[derive(Deserialize)]')
    parts.append('struct OpenUrlRequest ' + BL)
    parts.append('    url: String,')
    parts.append(BR)
    parts.append('')
    parts.append('async fn open_url(')
    parts.append('    State(_state): State<Arc<ServerState>>,')
    parts.append('    Json(req): Json<OpenUrlRequest>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    ' + chr(35) + chr(91) + 'cfg(target_os = ' + DQ + 'windows' + DQ + ')]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'cmd' + DQ + ').arg(' + DQ + '/c' + DQ + ').arg(' + DQ + 'start' + DQ + ').arg(&req.url).creation_flags(0x08000000).spawn();')
    parts.append('    ' + BR)
    parts.append('    ' + chr(35) + chr(91) + 'cfg(target_os = ' + DQ + 'macos' + DQ + ')]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'open' + DQ + ').arg(&req.url).spawn();')
    parts.append('    ' + BR)
    parts.append('    ' + chr(35) + chr(91) + 'cfg(all(unix, not(target_os = ' + DQ + 'macos' + DQ + ')))]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        let _ = Command::new(' + DQ + 'xdg-open' + DQ + ').arg(&req.url).spawn();')
    parts.append('    ' + BR)
    parts.append('    raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true' + BR + '))')
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_chunk5()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk5.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk5:', len(text), 'chars')

def make_chunk6():
    parts = []
    parts.append('')
    parts.append('async fn browse_folder(')
    parts.append('    State(_state): State<Arc<ServerState>>,')
    parts.append(') -> impl IntoResponse ' + BL)
    parts.append('    ' + chr(35) + chr(91) + 'cfg(target_os = ' + DQ + 'windows' + DQ + ')]')
    parts.append('    ' + BL)
    parts.append('        use std::process::Command;')
    parts.append('        use std::process::Stdio;')
    parts.append('        let script = ' + DQ + 'Add-Type -AssemblyName System.Windows.Forms;  = New-Object System.Windows.Forms.FolderBrowserDialog; .Description = ' + DQ + DQ + 'Select a folder' + DQ + DQ + '; if (.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) { .SelectedPath } else { ' + DQ + DQ + DQ + ' }' + DQ + ';')
    parts.append('        let output = Command::new(' + DQ + 'powershell' + DQ + ')')
    parts.append('            .arg(' + DQ + '-NoProfile' + DQ + ')')
    parts.append('            .arg(' + DQ + '-Command' + DQ + ')')
    parts.append('            .arg(script)')
    parts.append('            .creation_flags(0x08000000)')
    parts.append('            .stdout(Stdio::piped())')
    parts.append('            .stderr(Stdio::piped())')
    parts.append('            .output();')
    parts.append('        match output ' + BL)
    parts.append('            Ok(out) => ' + BL)
    parts.append('                let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();')
    parts.append('                if stdout.is_empty() ' + BL)
    parts.append('                    raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': false, ' + DQ + 'path' + DQ + ': ' + DQ + DQ + BR + '))')
    parts.append('                ' + BR + ' else ' + BL)
    parts.append('                    raw_json(serde_json::json!(' + BL + DQ + 'ok' + DQ + ': true, ' + DQ + 'path' + DQ + ': stdout' + BR + '))')
    parts.append('                ' + BR)
    parts.append('            ' + BR)
    parts.append('            Err(_) => json_err(StatusCode::INTERNAL_SERVER_ERROR, ' + DQ + 'Failed to run dialog' + DQ + '),')
    parts.append('        ' + BR)
    parts.append('    ' + BR)
    parts.append('    ' + chr(35) + chr(91) + 'cfg(not(target_os = ' + DQ + 'windows' + DQ + '))]')
    parts.append('    ' + BL)
    parts.append('        json_err(StatusCode::NOT_IMPLEMENTED, ' + DQ + 'browse-folder not supported' + DQ + ')')
    parts.append('    ' + BR)
    parts.append(BR)
    return chr(10).join(parts) + chr(10)

text = make_chunk6()
encoded = base64.b64encode(text.encode('utf-8')).decode('ascii')
with open('d:/game/mytemple/h_chunk6.b64', 'w') as f:
    f.write(encoded)
print('Wrote h_chunk6:', len(text), 'chars')
